### ISSUE TITLE
Dependencies incorrect in setup.py

### ISSUE THREAD

**Issue by j4mie** [epio/mantrid#5]
`mantrid-client` depends on `httplib2`, but this isn't specified in `setup.py`, so it won't work out of the box.

Also, `pip install mantrid` on my machine doesn't install its dependencies at all - I had to manually install `eventlet` for it to work. I think this is because the argument to `setup` should be `install_requires`, not `requires`.

**Comment by andrewgodwin** [comment]
Fixed.
